version: '3'
services:
  cheat-api:
    build:
      context: ./app
    ports:
      - "5000:5000"  # Adjust the port if needed
    container_name: cheat-api
    volumes:
      - "./app/static:/src/static"  # Mount the static folder from host to container


  cheat-front:
    build:
      context: ./front
    ports:
      - "8501:8501"  # Adjust the port if needed
    container_name: cheat-front

  cheat-redis:
    image: redis
    ports:
      - "6379:6379"  # Map Redis default port
    container_name: cheat-redis
